#!/usr/bin/env python3
"""Derive the Nav2 + DWB baseline configuration from the PS-VSP navigation.yaml.

    python3 make_dwb_yaml.py <navigation.yaml> <output.yaml>

Exactly two things change; everything else (AMCL, NavFn A*, goal checker,
inflation, velocity smoother, collision monitor, behaviours) is copied as is:

  1. controller_server.FollowPath: HumanAwareController1 -> dwb_core::DWBLocalPlanner
     with the Nav2 default critics and the same speed and acceleration limits.
  2. The social layer (aghpm_social_layer) is removed from the local and the
     global costmap, so people are seen only as lidar obstacles.

The baseline is therefore a human-unaware Nav2 stack on the same robot.
"""
import sys
import yaml

SOCIAL_LAYER = 'aghpm_social_layer'


def dwb_params(old, smoother, goal_checker):
    """DWB with Nav2's documented default critics; limits taken from the
    PS-VSP configuration so both planners work under the same constraints."""
    v_max = float(old['max_linear_vel'])
    w_max = float(old['max_angular_vel'])
    acc_x, _, acc_w = [float(a) for a in smoother['max_accel']]
    dec_x, _, dec_w = [float(a) for a in smoother['max_decel']]
    return {
        'plugin': 'dwb_core::DWBLocalPlanner',
        'debug_trajectory_details': False,
        'min_vel_x': 0.0,               # Nav2 default: DWB does not reverse
        'min_vel_y': 0.0,
        'max_vel_x': v_max,
        'max_vel_y': 0.0,
        'max_vel_theta': w_max,
        'min_speed_xy': 0.0,
        'max_speed_xy': v_max,
        'min_speed_theta': 0.0,
        'acc_lim_x': acc_x,
        'acc_lim_y': 0.0,
        'acc_lim_theta': acc_w,
        'decel_lim_x': dec_x,
        'decel_lim_y': 0.0,
        'decel_lim_theta': dec_w,
        'vx_samples': 20,
        'vy_samples': 5,
        'vtheta_samples': 20,
        'sim_time': 1.7,
        'linear_granularity': 0.05,
        'angular_granularity': 0.025,
        'transform_tolerance': 0.2,
        'xy_goal_tolerance': float(goal_checker['xy_goal_tolerance']),
        'trans_stopped_velocity': 0.25,
        'short_circuit_trajectory_evaluation': True,
        'stateful': True,
        'critics': ['RotateToGoal', 'Oscillation', 'BaseObstacle', 'GoalAlign',
                    'PathAlign', 'PathDist', 'GoalDist'],
        'BaseObstacle.scale': 0.02,
        'PathAlign.scale': 32.0,
        'PathAlign.forward_point_distance': 0.1,
        'GoalAlign.scale': 24.0,
        'GoalAlign.forward_point_distance': 0.1,
        'PathDist.scale': 32.0,
        'GoalDist.scale': 24.0,
        'RotateToGoal.scale': 32.0,
        'RotateToGoal.slowing_factor': 5.0,
        'RotateToGoal.lookahead_time': -1.0,
    }


def convert(params):
    ctrl = params['controller_server']['ros__parameters']
    old = ctrl['FollowPath']
    if 'HumanAwareController' not in old['plugin']:
        raise SystemExit(f"unexpected controller plugin: {old['plugin']}")
    ctrl['FollowPath'] = dwb_params(
        old, params['velocity_smoother']['ros__parameters'], ctrl['general_goal_checker'])
    for name in ('local_costmap', 'global_costmap'):
        cm = params[name][name]['ros__parameters']
        if SOCIAL_LAYER not in cm['plugins']:
            raise SystemExit(f'{name}: {SOCIAL_LAYER} not in plugins')
        cm['plugins'] = [p for p in cm['plugins'] if p != SOCIAL_LAYER]
        cm.pop(SOCIAL_LAYER, None)
    return params


def changed_keys(a, b, prefix=''):
    keys = []
    for k in sorted(set(a) | set(b), key=str):
        if k not in a or k not in b:
            keys.append(prefix + str(k))
        elif isinstance(a[k], dict) and isinstance(b[k], dict):
            keys += changed_keys(a[k], b[k], prefix + str(k) + '.')
        elif a[k] != b[k]:
            keys.append(prefix + str(k))
    return keys


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    src = yaml.safe_load(open(sys.argv[1]))
    out = convert(yaml.safe_load(open(sys.argv[1])))
    allowed = ('controller_server.ros__parameters.FollowPath',
               'local_costmap.local_costmap.ros__parameters.plugins',
               'local_costmap.local_costmap.ros__parameters.' + SOCIAL_LAYER,
               'global_costmap.global_costmap.ros__parameters.plugins',
               'global_costmap.global_costmap.ros__parameters.' + SOCIAL_LAYER)
    stray = [k for k in changed_keys(src, out) if not k.startswith(allowed)]
    if stray:
        raise SystemExit(f'unexpected differences: {stray}')
    with open(sys.argv[2], 'w') as f:
        f.write('# GENERATED by analysis/baseline/make_dwb_yaml.py -- Nav2 + DWB baseline.\n')
        yaml.safe_dump(out, f, default_flow_style=False, sort_keys=False)
    print(f'wrote {sys.argv[2]}: DWB controller, social layer removed from both costmaps')


if __name__ == '__main__':
    main()
